## Matrix Multiplication


# Rules for Matrix Multiplication

### **1. Dimension rule (compatibility)**

If

$$
A \in \mathbb{R}^{m \times n}, \quad B \in \mathbb{R}^{n \times p}
$$

then their product is defined as:

$$
C = AB \in \mathbb{R}^{m \times p}
$$


<br><br><br>

 **The inner dimensions must match** (the number of columns in $A$ = the number of rows in $B$).
The result takes the **outer dimensions**.



### ** Element rule (dot product)**

Each entry of the result matrix $C$ is computed as:

$$
C_{ij} = \sum_{k=1}^n A_{ik} \cdot B_{kj}
$$

That means:

* Row $i$ of $A$
* Dot product with column $j$ of $B$.



# Example

Let’s multiply

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

Both are $2 \times 2$, so result is also $2 \times 2$.

$$
C_{11} = (1)(5) + (2)(7) = 19
$$

$$
C_{12} = (1)(6) + (2)(8) = 22
$$

$$
C_{21} = (3)(5) + (4)(7) = 43
$$

$$
C_{22} = (3)(6) + (4)(8) = 50
$$

So:

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$


In [26]:
import torch

In [27]:
torch.manual_seed(22)

In [20]:
A = torch.rand(5,2)
A

tensor([[0.3659, 0.7025],
        [0.3104, 0.0097],
        [0.6577, 0.1947],
        [0.9506, 0.6887],
        [0.8174, 0.7575]])

In [21]:
B = torch.rand(2,5)
B

tensor([[0.7492, 0.6874, 0.2564, 0.0672, 0.9066],
        [0.9175, 0.4236, 0.7978, 0.8594, 0.3660]])

In [22]:
C = torch.matmul(A,B)
C

tensor([[0.9187, 0.5491, 0.6543, 0.6284, 0.5889],
        [0.2414, 0.2174, 0.0873, 0.0292, 0.2849],
        [0.6714, 0.5346, 0.3239, 0.2115, 0.6675],
        [1.3441, 0.9452, 0.7932, 0.6559, 1.1139],
        [1.3074, 0.8827, 0.8139, 0.7060, 1.0183]])


## Transpose Matrix

Now when we want to transpose a 2 dim matrix with can use the .t() function or id the dim > 2 then we need to use torch.transpose(x,0,1)

In [28]:
C.t()

tensor([[0.9187, 0.2414, 0.6714, 1.3441, 1.3074],
        [0.5491, 0.2174, 0.5346, 0.9452, 0.8827],
        [0.6543, 0.0873, 0.3239, 0.7932, 0.8139],
        [0.6284, 0.0292, 0.2115, 0.6559, 0.7060],
        [0.5889, 0.2849, 0.6675, 1.1139, 1.0183]])